import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync,readdirSync } from 'node:fs';
import { createServer } from 'node:http';
import worker from './dist/server/index.js';
import { client } from './dist/server/boards-client.js';
import { adminKeyFor } from './dist/server/admin-login.js';
import { runRankingProtectionChecks } from './check-ranking-protection.mjs';
import { runScheduleChecks } from './check-schedule.mjs';
import { runWeeklyResultsChecks } from './check-weekly-results.mjs';
import { runMatchProgressChecks } from './check-match-progress.mjs';
import { runLiveCourtsChecks } from './check-live-courts.mjs';
import { runProgressUIChecks } from './check-progress-ui.mjs';
import { runLiveUIChecks } from './check-live-ui.mjs';
import { runServerAuditChecks } from './check-server-audit.mjs';
import { runClientAuditChecks } from './check-client-audit.mjs';
import { runSubstitutionChecks } from './check-substitution.mjs';
import { runEmergencyUIChecks } from './check-emergency-ui.mjs';
import { runOperatorNavChecks } from './check-operator-nav.mjs';
const db=new DatabaseSync(':memory:');
for(const name of readdirSync(new URL('./drizzle/',import.meta.url)).filter(n=>n.endsWith('.sql')).sort())db.exec(readFileSync(new URL('./drizzle/'+name,import.meta.url),'utf8'));
const DB={prepare(sql){let params=[];const statement=db.prepare(sql);return {bind(...values){params=values;return this;},async first(){return statement.get(...params)||null;},async run(){return {meta:statement.run(...params)};},async all(){return {results:statement.all(...params)};},execute(){return /^\s*(SELECT|WITH)\b/i.test(sql)?{results:statement.all(...params)}:{meta:statement.run(...params)};}};},async batch(statements){db.exec('BEGIN');try{const out=statements.map(s=>s.execute());db.exec('COMMIT');return out;}catch(error){db.exec('ROLLBACK');throw error;}}};
const env={DB,EDITOR_KEY:'test-editor-key',OPERATOR_PASSWORD:'test-password',ADMIN_PASSWORD:'admin-pass'};
const origin='http://localhost:4173';
const login=(password,headers={})=>worker.fetch(new Request(origin+'/api/operator-login',{method:'POST',headers:{origin,'content-type':'application/json','cf-connecting-ip':'test-client',...headers},body:JSON.stringify({password})}),env);
new Function('return ('+client.toString()+')');
assert.ok(client.toString().includes('id="addGuest"')&&client.toString().includes('adhoc'),'openPicker에 즉석 게스트 추가 기능이 있어야 합니다');
assert.ok(client.toString().includes('id="deletePost"'),'상세 화면에 삭제 버튼이 있어야 합니다');
assert.ok(client.toString().includes('personEditForm')&&client.toString().includes('/api/people/update')&&client.toString().includes('/api/people/history'),'운영진 사람 정보 수정·변경 이력 UI가 있어야 합니다');
const noticeStart=client.toString().indexOf('function noticeHTML'),noticeEnd=client.toString().indexOf('let people',noticeStart),renderNotice=new Function('esc',client.toString().slice(noticeStart,noticeEnd)+';return noticeHTML;')(s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;'));
const noticeRendered=renderNotice('1. 첫 제목\n[소제목]\n🔴 쿠폰 누락자 및 미지급자\n2. 둘째 제목\n🔵 강조 메모\n<script>alert(1)</script>');
assert.equal(noticeRendered,'<h2 class="nb-section"><span class="nb-num">1</span><span>첫 제목</span></h2><h3 class="nb-sub">소제목</h3><h2 class="nb-section nb-section-alert"><span>쿠폰 누락자 및 미지급자</span></h2><h2 class="nb-section"><span class="nb-num">2</span><span>둘째 제목</span></h2><p class="nb-note">🔵 강조 메모</p><p>&lt;script&gt;alert(1)&lt;/script&gt;</p>','공지 heading renderer는 🔴 경고 제목·기존 heading·메모·escaping을 보존해야 합니다');
assert.equal((await login('wrong')).status,401);
const accepted=await login('test-password');assert.equal(accepted.status,200);assert.equal((await accepted.json()).redirect,'/operate-test-editor-key');
assert.equal((await login('test-password',{origin:'https://untrusted.example'})).status,403);
for(let i=0;i<5;i++)assert.equal((await login('wrong')).status,401);
assert.equal((await login('test-password')).status,429);
db.exec('UPDATE operator_login_limits SET expires_at=0');
assert.equal((await login('test-password')).status,200);
const html=await (await worker.fetch(new Request(origin),env)).text();
assert.ok(html.includes('운영진권한'));assert.ok(!html.includes(env.OPERATOR_PASSWORD));assert.ok(!html.includes(env.EDITOR_KEY));
assert.ok(html.includes('콕끼리 Since 2026.05.08. 우리가 함께한지 <strong id="daysTogether">-</strong>일'));
assert.ok(html.includes('.days-together strong{color:#03a84e'));
assert.ok(html.includes('Intl.DateTimeFormat'));
assert.ok(!html.includes('<nav class="operator-nav"'),'public pages must not render operator navigation');
const operatorHtml=await (await worker.fetch(new Request(origin+'/operate-'+env.EDITOR_KEY),env)).text();
assert.ok(operatorHtml.includes('<nav class="operator-nav"'),'operator pages must render the persistent navigation');
assert.ok(operatorHtml.includes('class="operator-layout"'),'operator layout must reserve room for its sidebar');
const rankings=await worker.fetch(new Request(origin+'/api/rankings'),env);assert.equal(rankings.status,200);const rankingData=await rankings.json();assert.equal(rankingData.items.length,61);assert.equal(rankingData.source,'콕끼리 시드 관리표.xlsx');assert.equal(rankingData.sourceDate,'2026-09-10');assert.equal(rankingData.updatedDate,'2026-09-10');
const sio=rankingData.items.find(row=>row.name==='시오'),newMember=rankingData.items.find(row=>row.name==='호잇');assert.equal(sio.points,99);assert.equal(sio.seed,'B+');assert.equal(newMember.points,123);assert.equal(newMember.seed,'A+');
// 주밤(115)·로토(104): the sheet said A+, the operator confirmed A on 2026-09-12; seeds follow the points rule everywhere, including the roster shown to operators.
const jubam=rankingData.items.find(row=>row.name==='주밤'),roto=rankingData.items.find(row=>row.name==='로토');assert.equal(jubam.points,115);assert.equal(jubam.seed,'A');assert.equal(roto.points,104);assert.equal(roto.seed,'A');
const peopleData=await (await worker.fetch(new Request(origin+'/api/people'),env)).json();assert.equal(peopleData.people.find(p=>p.name==='주밤').seed,'A');assert.equal(peopleData.people.find(p=>p.name==='로토').seed,'A');
const guestPeople=peopleData.people.filter(p=>p.type==='guest');assert.equal(guestPeople.length,35);assert.ok(guestPeople.every(p=>Number.isInteger(p.points)&&p.points>=20));assert.equal(guestPeople.find(p=>p.name==='몽구').points,125);assert.equal(guestPeople.find(p=>p.name==='우니').points,20);
// 요청 045: 회원 명단의 (부재)·(서울) 표기 제거
assert.ok(rankingData.items.every(r=>!/\((?:서울|부재)\)/.test(r.name)),'회원 랭킹 이름에 (부재)/(서울)가 없어야 합니다');
assert.equal(rankingData.items.find(r=>r.name==='덕자').points,60);assert.equal(rankingData.items.find(r=>r.name==='우민').points,40);
assert.ok(!rankingData.items.some(r=>r.name==='덕자(부재)'||r.name==='우민(부재)'));
for(const nm of ['민석','민수','호구','우주','윤후'])assert.ok(guestPeople.some(p=>p.name===nm),nm+' 게스트 이름이 정리되어야 합니다');
// 겹치는 이름은 지역 표기를 남긴다(회색 작은 글씨로 렌더링): 회원 철 vs 게스트 철, 게스트 선호 2명
assert.ok(guestPeople.some(p=>p.name==='철(서울)'),'겹치는 철은 지역 표기 유지');
assert.ok(guestPeople.some(p=>p.name==='선호(서울)')&&guestPeople.some(p=>p.name==='선호'),'겹치는 선호는 둘 다 존재');
const memberPeople=peopleData.people.filter(p=>p.type==='member');assert.ok(memberPeople.every(p=>Number.isInteger(p.points)));assert.equal(memberPeople.find(p=>p.name==='호잇').points,123);
// 요청 060: 시드현황 사람 추가/삭제(회원·게스트)
const addP=(name,type,points,key=env.EDITOR_KEY)=>worker.fetch(new Request(origin+'/api/people',{method:'POST',headers:{'content-type':'application/json',...(key?{'x-kokkiri-editor':key}:{})},body:JSON.stringify({name,type,points})}),env);
assert.equal((await addP('추가회원','member',55,null)).status,403);
const addM=await addP('추가회원','member',55);assert.equal(addM.status,200);const addMId=(await addM.json()).data.id;
const rkA=await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json();assert.equal(rkA.items.length,62);assert.ok(rkA.items.some(r=>r.name==='추가회원'&&r.seed==='D+'));
assert.equal((await addP('추가회원','member',20)).status,409);
const memberInfo=(await (await worker.fetch(new Request(origin+'/api/people'),env)).json()).people.find(p=>p.name==='추가회원');
const updateP=(body,key=env.EDITOR_KEY)=>worker.fetch(new Request(origin+'/api/people/update',{method:'POST',headers:{'content-type':'application/json',...(key?{'x-kokkiri-editor':key}:{})},body:JSON.stringify(body)}),env);
assert.equal((await updateP({id:memberInfo.id,type:'member',name:'추가회원',points:65,reason:'최신 기준표 반영',expectedVersion:memberInfo.edit_version},null)).status,403);
const updatedMember=await updateP({id:memberInfo.id,type:'member',name:'추가회원',points:65,reason:'최신 기준표 반영',expectedVersion:memberInfo.edit_version});assert.equal(updatedMember.status,200);assert.equal((await updatedMember.json()).data.seed,'C');
assert.equal((await updateP({id:memberInfo.id,type:'member',name:'추가회원',points:70,reason:'오래된 화면 저장',expectedVersion:memberInfo.edit_version})).status,409);
const memberHistory=await (await worker.fetch(new Request(origin+'/api/people/history?type=member&id='+encodeURIComponent(memberInfo.id),{headers:{'x-kokkiri-editor':env.EDITOR_KEY}}),env)).json();assert.ok(memberHistory.items.some(h=>h.action==='update'&&h.after_points===65&&h.reason==='최신 기준표 반영'));
const addG=await addP('추가게스트','guest',30);assert.equal(addG.status,200);const addGId=(await addG.json()).data.id;
const guestInfo=(await (await worker.fetch(new Request(origin+'/api/people'),env)).json()).people.find(p=>p.id===addGId);const updatedGuest=await updateP({id:addGId,type:'guest',name:'추가게스트',points:40,reason:'게스트 시드 재확인',expectedVersion:guestInfo.edit_version});assert.equal(updatedGuest.status,200);assert.equal((await updatedGuest.json()).data.seed,'D');
const guestHistory=await (await worker.fetch(new Request(origin+'/api/people/history?type=guest&id='+encodeURIComponent(addGId),{headers:{'x-kokkiri-editor':env.EDITOR_KEY}}),env)).json();assert.ok(guestHistory.items.some(h=>h.action==='update'&&h.after_points===40));
const ppA=(await (await worker.fetch(new Request(origin+'/api/people'),env)).json()).people;assert.ok(ppA.some(p=>p.name==='추가게스트'&&p.type==='guest'&&p.points===40&&p.seed==='D'));assert.equal(ppA.filter(p=>p.type==='guest').length,36);
assert.equal((await worker.fetch(new Request(origin+'/api/people/hide',{method:'POST',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({ids:[addMId,addGId]})}),env)).status,200);
const rkB=await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json();assert.equal(rkB.items.length,61);assert.ok(!rkB.items.some(r=>r.name==='추가회원'));
assert.ok(rkB.items.map(r=>r.rank).every((v,i)=>v===i+1),'삭제 후에도 회원 순위가 1..N 연속이어야 합니다');
const ppB=(await (await worker.fetch(new Request(origin+'/api/people'),env)).json()).people;assert.equal(ppB.filter(p=>p.type==='guest').length,35);assert.equal(ppB.filter(p=>p.type==='member').length,61);
assert.equal((await worker.fetch(new Request(origin+'/api/people/hide',{method:'POST'}),env)).status,403);
const schedule={id:'ranking-test',kind:'schedule',version:0,title:'점수 계산 테스트',names:['시오','구구','구름','백구'],participantIds:['member-10','member-17','member-16','member-18'],courts:1,rounds:1,schedule:[{round:1,g:[['시오','구구','구름','백구']],rest:[]}],results:{}};
const put=(version,data)=>worker.fetch(new Request(origin+'/api/posts/ranking-test',{method:'PUT',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({kind:'schedule',version,operation:crypto.randomUUID(),data})}),env);
assert.equal((await put(0,schedule)).status,200);schedule.version=1;schedule.results={'0-0':'a'};const saved=await put(1,schedule);assert.equal(saved.status,200);const savedData=(await saved.json()).data;const settled=await worker.fetch(new Request(origin+'/api/posts/ranking-test/settle',{method:'POST',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({version:savedData.version,operation:'settle-test'})}),env);assert.equal(settled.status,200);const settledData=(await settled.json()).data;assert.equal(settledData.settledAt!==undefined,true);const afterRankings=await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json();const after=afterRankings.items;assert.equal(afterRankings.updatedDate,new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Seoul'}));assert.equal(after.find(row=>row.name==='시오').points,101);assert.equal(after.find(row=>row.name==='구구').points,90);assert.equal(after.find(row=>row.name==='구름').points,89);assert.equal(after.find(row=>row.name==='백구').points,88);assert.equal(after.find(row=>row.name==='시오').previous_points,99);assert.equal(after.find(row=>row.name==='시오').points-after.find(row=>row.name==='시오').previous_points,2);assert.equal(db.prepare('SELECT COUNT(*) AS count FROM ranking_events').get().count,4);assert.equal((await worker.fetch(new Request(origin+'/api/posts/ranking-test/settle',{method:'POST',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({version:settledData.version,operation:'settle-again'})}),env)).status,200);
assert.equal((await put(settledData.version,{...schedule,version:settledData.version,settledAt:settledData.settledAt})).status,409);
const delSchedule={...schedule,id:'delete-test',version:0,settledAt:null,results:{}};
assert.equal((await worker.fetch(new Request(origin+'/api/posts/delete-test',{method:'PUT',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({kind:'schedule',version:0,operation:crypto.randomUUID(),data:delSchedule})}),env)).status,200);
assert.equal((await worker.fetch(new Request(origin+'/api/posts/delete-test',{method:'DELETE'}),env)).status,403);
assert.equal((await worker.fetch(new Request(origin+'/api/posts/delete-test',{method:'DELETE',headers:{'x-kokkiri-editor':env.EDITOR_KEY}}),env)).status,200);
assert.equal((await worker.fetch(new Request(origin+'/api/posts/delete-test'),env)).status,404);
assert.equal((await worker.fetch(new Request(origin+'/api/posts/ranking-test',{method:'DELETE',headers:{'x-kokkiri-editor':env.EDITOR_KEY}}),env)).status,409);
// 요청 065: legacy-schedule는 삭제(마이그레이션 0008) 후 목록/상세를 조회해도 되살아나지 않는다(preserveLegacy 제거)
assert.equal((await worker.fetch(new Request(origin+'/api/posts/legacy-schedule'),env)).status,404);
assert.ok(!((await (await worker.fetch(new Request(origin+'/api/posts?kind=schedule'),env)).json()).items.some(p=>p.id==='legacy-schedule')));
// 요청 037·038·039: 라운드 방식 저장, 회원(공개) 결과 기록, 랜덤 라운드 제외 정산, MVP
const wave2={id:'wave2-test',kind:'schedule',version:0,title:'웨이브2 테스트',names:['시오','구구','구름','백구'],participantIds:['member-10','member-17','member-16','member-18'],courts:1,rounds:2,schedule:[{round:1,method:'balanced',g:[['시오','구구','구름','백구']],rest:[]},{round:2,method:'random',g:[['시오','구구','구름','백구']],rest:[]}],results:{}};
const putW2=(version,data)=>worker.fetch(new Request(origin+'/api/posts/wave2-test',{method:'PUT',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({kind:'schedule',version,operation:crypto.randomUUID(),data})}),env);
const postResult=body=>worker.fetch(new Request(origin+'/api/posts/wave2-test/result',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),env);
const getW2=async()=>(await (await worker.fetch(new Request(origin+'/api/posts/wave2-test'),env)).json()).data;
assert.equal((await putW2(0,wave2)).status,200);
// 요청 047·091: 새 대진 초안 생성은 최신 확정 주간 표시를 초기화하지 않는다
const afterCreate=(await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items,sioAC=afterCreate.find(r=>r.name==='시오');
assert.equal(sioAC.attendance,1);assert.equal(sioAC.wins,1);assert.equal(sioAC.losses,0);assert.equal(sioAC.points,101);
assert.equal(sioAC.previous_points,99);assert.equal(sioAC.points-sioAC.previous_points,2);
const w2got=await getW2();assert.equal(w2got.schedule[0].method,'balanced');assert.equal(w2got.schedule[1].method,'random');
assert.equal((await postResult({key:'1-0',winner:'a'})).status,400);
assert.equal((await postResult({key:'0-0',winner:'x'})).status,400);
assert.equal((await postResult({key:'0-0',winner:'a'})).status,200);
const beforeW=(await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items,bp=n=>beforeW.find(r=>r.name===n).points;
const sB=bp('시오'),gB=bp('구구'),rB=bp('구름'),bB=bp('백구');
const w2v=(await getW2()).version;
const w2settled=await worker.fetch(new Request(origin+'/api/posts/wave2-test/settle',{method:'POST',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({version:w2v,operation:'settle-wave2'})}),env);
assert.equal(w2settled.status,200);const w2data=(await w2settled.json()).data;
const afterW=(await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items,ap=n=>afterW.find(r=>r.name===n).points;
assert.equal(ap('시오')-sB,2);assert.equal(ap('구구')-gB,2);assert.equal(ap('구름')-rB,0);assert.equal(ap('백구')-bB,0);
assert.deepEqual([...w2data.mvp].sort(),['구구','시오']);
assert.equal(w2data.title,'웨이브2 테스트');assert.deepEqual([...w2data.mvp].sort(),['구구','시오']);// 요청 078: 마감해도 제목은 그대로, MVP는 mvp[]로만
assert.ok(w2data.settledAt);
const mvpApi=await (await worker.fetch(new Request(origin+'/api/mvp'),env)).json();
assert.equal(mvpApi.id,'wave2-test');assert.deepEqual([...mvpApi.mvp].sort(),['구구','시오']);assert.ok(mvpApi.settledAt);
// 요청 083: 목록에서 MVP를 표시하므로 상세와 같은 명단을 배열로 반환한다.
const w2List=(await (await worker.fetch(new Request(origin+'/api/posts?kind=schedule'),env)).json()).items.find(p=>p.id==='wave2-test');
assert.equal(w2List.title,'웨이브2 테스트');assert.equal(w2List.settledAt,w2data.settledAt);assert.deepEqual(w2List.mvp,w2data.mvp);
assert.equal(Object.hasOwn(w2List,'mvp_json'),false);
const noticeMvpList=(await (await worker.fetch(new Request(origin+'/api/posts?kind=notice'),env)).json()).items;
assert.ok(noticeMvpList.length>0);assert.ok(noticeMvpList.every(p=>Array.isArray(p.mvp)&&p.mvp.length===0));
assert.equal((await postResult({key:'0-0',winner:'b'})).status,409);
// 요청 053: 마감 취소(가장 최근 마감 되돌리기)
assert.equal((await worker.fetch(new Request(origin+'/api/posts/wave2-test/unsettle',{method:'POST'}),env)).status,403);
const beforeUn=(await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items,upBp=n=>beforeUn.find(r=>r.name===n).points;
assert.equal((await worker.fetch(new Request(origin+'/api/posts/wave2-test/unsettle',{method:'POST',headers:{'x-kokkiri-editor':env.EDITOR_KEY}}),env)).status,200);
const w2after=await getW2();assert.equal(w2after.settledAt,null);assert.deepEqual(w2after.mvp,[]);assert.ok(!(w2after.title||'').includes('MVP'));
const w2ListAfter=(await (await worker.fetch(new Request(origin+'/api/posts?kind=schedule'),env)).json()).items.find(p=>p.id==='wave2-test');
assert.equal(w2ListAfter.settledAt,null);assert.deepEqual(w2ListAfter.mvp,[]);
const afterUn=(await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items,unAp=n=>afterUn.find(r=>r.name===n).points;
assert.equal(upBp('시오')-unAp('시오'),2);assert.equal(upBp('구구')-unAp('구구'),2);
assert.equal((await worker.fetch(new Request(origin+'/api/posts/wave2-test/unsettle',{method:'POST',headers:{'x-kokkiri-editor':env.EDITOR_KEY}}),env)).status,400);
assert.equal((await worker.fetch(new Request(origin+'/api/posts/test',{method:'PUT',body:'{}'}),env)).status,403);
assert.equal((await worker.fetch(new Request(origin+'/operate-'+env.EDITOR_KEY),env)).status,200);
assert.equal((await worker.fetch(new Request(origin+'/api/operator-login',{method:'GET'}),env)).status,405);
assert.equal((await worker.fetch(new Request(origin+'/api/operator-login',{method:'POST',headers:{origin},body:'{}'}),{})).status,503);
// 요청 053: 마감 취소(unsettle) — 최근 마감 대진의 정산을 되돌려 점수·출석·승패 원복, settledAt 해제
const uSched={id:'unsettle-test',kind:'schedule',version:0,title:'마감취소 테스트',names:['시오','구구','구름','백구'],participantIds:['member-10','member-17','member-16','member-18'],courts:1,rounds:1,schedule:[{round:1,method:'balanced',g:[['시오','구구','구름','백구']],rest:[]}],results:{}};
assert.equal((await worker.fetch(new Request(origin+'/api/posts/unsettle-test',{method:'PUT',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({kind:'schedule',version:0,operation:crypto.randomUUID(),data:uSched})}),env)).status,200);
const uPre=(await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items.find(r=>r.name==='시오').points;
await worker.fetch(new Request(origin+'/api/posts/unsettle-test/result',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key:'0-0',winner:'a'})}),env);
const uv=(await (await worker.fetch(new Request(origin+'/api/posts/unsettle-test'),env)).json()).data.version;
assert.equal((await worker.fetch(new Request(origin+'/api/posts/unsettle-test/settle',{method:'POST',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({version:uv,operation:'u-settle'})}),env)).status,200);
const uSet=(await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items.find(r=>r.name==='시오');assert.equal(uSet.points,uPre+2);assert.equal(uSet.attendance,1);assert.equal(uSet.wins,1);
assert.equal((await worker.fetch(new Request(origin+'/api/posts/unsettle-test/unsettle',{method:'POST'}),env)).status,403);
assert.equal((await worker.fetch(new Request(origin+'/api/posts/unsettle-test/unsettle',{method:'POST',headers:{'x-kokkiri-editor':env.EDITOR_KEY}}),env)).status,200);
const uRev=(await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items.find(r=>r.name==='시오');assert.equal(uRev.points,uPre);assert.equal(uRev.attendance,1);assert.equal(uRev.wins,1);assert.equal(uRev.losses,0);
assert.equal((await (await worker.fetch(new Request(origin+'/api/posts/unsettle-test'),env)).json()).data.settledAt,null);
// 요청 062: 코트 추가(라운드 내 경기 수 가변·중복 배치) — 시오·구구·구름·백구가 한 라운드에 두 경기
const putV=(id,v,d)=>worker.fetch(new Request(origin+'/api/posts/'+id,{method:'PUT',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({kind:'schedule',version:v,operation:crypto.randomUUID(),data:d})}),env);
const vt={id:'court-test',kind:'schedule',version:0,title:'코트추가 테스트',names:['시오','구구','구름','백구'],participantIds:['member-10','member-17','member-16','member-18'],courts:1,rounds:1,schedule:[{round:1,method:'balanced',g:[['시오','구구','구름','백구'],['시오','구름','구구','백구']],rest:[]}],results:{'0-0':'a','0-1':'a'}};
assert.equal((await putV('court-test',0,vt)).status,200);
const cB=(await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items,cbp=n=>cB.find(r=>r.name===n).points;const cb={s:cbp('시오'),g:cbp('구구'),r:cbp('구름'),b:cbp('백구')};
assert.equal((await worker.fetch(new Request(origin+'/api/posts/court-test/settle',{method:'POST',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({version:1,operation:'settle-court'})}),env)).status,200);
const cA=(await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items,cap2=n=>cA.find(r=>r.name===n).points;
assert.equal(cap2('시오')-cb.s,3);assert.equal(cap2('구구')-cb.g,1);assert.equal(cap2('구름')-cb.r,1);assert.equal(cap2('백구')-cb.b,-1);
// 요청 061: 불참(무효 경기) — 백구 불참 → 백구 낀 경기 무효, 백구 출석 0, 시오는 출석만
const ab={id:'absent-test',kind:'schedule',version:0,title:'불참 테스트',names:['호잇','뚜기','주밤','로토','시오','구구','구름','백구'],participantIds:['member-4','member-5','member-6','member-7','member-10','member-17','member-16','member-18'],courts:2,rounds:1,schedule:[{round:1,method:'balanced',g:[['호잇','뚜기','주밤','로토'],['시오','구구','구름','백구']],rest:[]}],results:{'0-0':'a','0-1':'a'},absent:['백구']};
assert.equal((await putV('absent-test',0,ab)).status,200);
assert.equal((await worker.fetch(new Request(origin+'/api/posts/absent-test/result',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key:'0-1',winner:'a'})}),env)).status,400);
const aB=(await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items,abp=n=>aB.find(r=>r.name===n).points;const abv={h:abp('호잇'),t:abp('뚜기'),j:abp('주밤'),l:abp('로토'),s:abp('시오'),b:abp('백구')};
assert.equal((await worker.fetch(new Request(origin+'/api/posts/absent-test/settle',{method:'POST',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({version:1,operation:'settle-abs'})}),env)).status,200);
const aA=(await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items,aap=n=>aA.find(r=>r.name===n).points;
assert.equal(aap('호잇')-abv.h,2);assert.equal(aap('뚜기')-abv.t,2);assert.equal(aap('주밤')-abv.j,0);assert.equal(aap('로토')-abv.l,0);assert.equal(aap('시오')-abv.s,1);assert.equal(aap('백구')-abv.b,0);
// 요청 063: 9월 12일 토요일 정모 대진표(마이그레이션 게시) 로드·정산 검증
const jm=(await (await worker.fetch(new Request(origin+'/api/posts/jeongmo-2026-09-12'),env)).json()).data;
assert.equal(jm.title,'9월 12일 토요일 정모');assert.equal(jm.names.length,28);assert.equal(jm.schedule.length,5);assert.deepEqual(jm.absent,['텐텐']);assert.equal(jm.schedule[4].g.length,8);
const jmGuests=(await (await worker.fetch(new Request(origin+'/api/people'),env)).json()).people.filter(p=>p.type==='guest'&&['아식스','제냐','허니'].includes(p.name));assert.equal(jmGuests.length,3);assert.equal(jmGuests.find(p=>p.name==='아식스').seed,'A');
const jmB=(await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items,jbp=n=>{const r=jmB.find(x=>x.name===n);return r?r.points:null;};
const rotoB=jbp('로토'),chilB=jbp('곽동칠');
const jmSettle=await worker.fetch(new Request(origin+'/api/posts/jeongmo-2026-09-12/settle',{method:'POST',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({version:jm.version,operation:'settle-jeongmo'})}),env);
assert.equal(jmSettle.status,200);const jmData=(await jmSettle.json()).data;
const jmA=(await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items,jap=n=>jmA.find(x=>x.name===n).points;
assert.equal(jap('로토')-rotoB,5);assert.equal(jap('곽동칠')-chilB,-3);
assert.deepEqual([...jmData.mvp].sort(),['동이','로토','소고기','시오','슝슝이','야키'].sort());
// 요청 068·069: 게스트도 정산 점수 변동 대상 + 회원 이관
const gsAdd=await worker.fetch(new Request(origin+'/api/people',{method:'POST',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({name:'점수게스트',type:'guest',points:30})}),env);
assert.equal(gsAdd.status,200);const gsId=(await gsAdd.json()).data.id;
const gsPre=(await (await worker.fetch(new Request(origin+'/api/people'),env)).json()).people.find(p=>p.id===gsId);
assert.equal(gsPre.points,30);assert.equal(gsPre.previous_points,30);assert.equal(gsPre.attendance,0);
const gsSched={id:'guest-score',kind:'schedule',version:0,title:'게스트 점수',names:['점수게스트','시오','구구','구름'],participantIds:[gsId,'member-10','member-17','member-16'],courts:1,rounds:1,schedule:[{round:1,method:'balanced',g:[['점수게스트','시오','구구','구름']],rest:[]}],results:{}};
assert.equal((await putV('guest-score',0,gsSched)).status,200);
await worker.fetch(new Request(origin+'/api/posts/guest-score/result',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key:'0-0',winner:'a'})}),env);
const gsVer=(await (await worker.fetch(new Request(origin+'/api/posts/guest-score'),env)).json()).data.version;
const gsSettle=await worker.fetch(new Request(origin+'/api/posts/guest-score/settle',{method:'POST',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({version:gsVer,operation:'settle-gsc'})}),env);
assert.equal(gsSettle.status,200);const gsSettleData=(await gsSettle.json()).data;
const gsAfter=(await (await worker.fetch(new Request(origin+'/api/people'),env)).json()).people.find(p=>p.id===gsId);
assert.equal(gsAfter.points,32);assert.equal(gsAfter.previous_points,30);assert.equal(gsAfter.attendance,1);assert.equal(gsAfter.wins,1);assert.equal(gsAfter.losses,0);
assert.ok(!gsSettleData.mvp.includes('점수게스트'));assert.deepEqual([...gsSettleData.mvp].sort(),['시오']);
assert.equal((await worker.fetch(new Request(origin+'/api/posts/guest-score/unsettle',{method:'POST',headers:{'x-kokkiri-editor':env.EDITOR_KEY}}),env)).status,200);
const gsRev=(await (await worker.fetch(new Request(origin+'/api/people'),env)).json()).people.find(p=>p.id===gsId);
assert.equal(gsRev.points,30);assert.equal(gsRev.attendance,0);assert.equal(gsRev.wins,0);assert.equal(gsRev.losses,0);
const gsVer2=(await (await worker.fetch(new Request(origin+'/api/posts/guest-score'),env)).json()).data.version;
assert.equal((await worker.fetch(new Request(origin+'/api/posts/guest-score/settle',{method:'POST',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({version:gsVer2,operation:'settle-gsc2'})}),env)).status,200);
assert.equal((await worker.fetch(new Request(origin+'/api/people/promote',{method:'POST'}),env)).status,403);
assert.equal((await worker.fetch(new Request(origin+'/api/people/promote',{method:'POST',headers:{'content-type':'application/json','x-kokkiri-editor':env.EDITOR_KEY},body:JSON.stringify({ids:[gsId]})}),env)).status,200);
const gsAfterProm=(await (await worker.fetch(new Request(origin+'/api/people'),env)).json()).people;
assert.ok(!gsAfterProm.some(p=>p.id===gsId));
const gsPromMember=(await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items.find(r=>r.name==='점수게스트');
assert.ok(gsPromMember);assert.equal(gsPromMember.points,32);assert.equal(gsPromMember.wins,1);assert.equal(gsPromMember.attendance,1);
// 요청 073·074: 홈페이지 관리자 — 로그인·운영진 임명/해제·백업
const adminKey=await adminKeyFor(env);
assert.equal((await worker.fetch(new Request(origin+'/api/admin-login',{method:'POST',headers:{origin,'content-type':'application/json','cf-connecting-ip':'admin-client'},body:JSON.stringify({password:'nope'})}),env)).status,401);
const adminOk=await worker.fetch(new Request(origin+'/api/admin-login',{method:'POST',headers:{origin,'content-type':'application/json','cf-connecting-ip':'admin-client'},body:JSON.stringify({password:'admin-pass'})}),env);
assert.equal(adminOk.status,200);assert.equal((await adminOk.json()).redirect,'/administrate-'+adminKey);
const rkAll=(await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items;
assert.equal(rkAll.find(r=>r.name==='로토').is_operator,1);
const opTarget=rkAll.find(r=>r.name==='구름');assert.equal(opTarget.is_operator,0);
assert.equal((await worker.fetch(new Request(origin+'/api/operator-role',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({memberId:opTarget.member_id,on:1})}),env)).status,403);
assert.equal((await worker.fetch(new Request(origin+'/api/operator-role',{method:'POST',headers:{'content-type':'application/json','x-kokkiri-admin':adminKey},body:JSON.stringify({memberId:opTarget.member_id,on:1})}),env)).status,200);
assert.equal((await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items.find(r=>r.name==='구름').is_operator,1);
await worker.fetch(new Request(origin+'/api/operator-role',{method:'POST',headers:{'content-type':'application/json','x-kokkiri-admin':adminKey},body:JSON.stringify({memberId:opTarget.member_id,on:0})}),env);
assert.equal((await (await worker.fetch(new Request(origin+'/api/rankings'),env)).json()).items.find(r=>r.name==='구름').is_operator,0);
assert.equal((await worker.fetch(new Request(origin+'/administrate-'+adminKey),env)).status,200);
assert.equal((await worker.fetch(new Request(origin+'/api/backups'),env)).status,403);
const bkPost=await worker.fetch(new Request(origin+'/api/backups',{method:'POST',headers:{'x-kokkiri-admin':adminKey}}),env);
assert.equal(bkPost.status,200);const bkId=(await bkPost.json()).data.id;
const bkList=(await (await worker.fetch(new Request(origin+'/api/backups',{headers:{'x-kokkiri-admin':adminKey}}),env)).json()).items;
assert.ok(bkList.some(b=>b.id===bkId));
const bkDl=await worker.fetch(new Request(origin+'/api/backups/'+bkId,{headers:{'x-kokkiri-admin':adminKey}}),env);
assert.equal(bkDl.status,200);const bkData=JSON.parse(await bkDl.text());assert.ok(Array.isArray(bkData.posts)&&Array.isArray(bkData.members)&&Array.isArray(bkData.guests));
assert.ok(Array.isArray(bkData.settlements)&&bkData.settlements.some(row=>row.schedule_id==='guest-score'),'백업에 최신 정산 원본이 포함되어야 합니다');
assert.ok(Array.isArray(bkData.rankingEvents)&&bkData.rankingEvents.some(row=>row.schedule_id==='guest-score'),'백업에 최신 회원 정산 이벤트가 포함되어야 합니다');
assert.ok(Array.isArray(bkData.guestEvents)&&bkData.guestEvents.some(row=>row.schedule_id==='guest-score'),'백업에 최신 게스트 정산 이벤트가 포함되어야 합니다');
await worker.scheduled({cron:'0 0 * * 0'},env,{waitUntil(){}});
assert.ok((await (await worker.fetch(new Request(origin+'/api/backups',{headers:{'x-kokkiri-admin':adminKey}}),env)).json()).items.length>=2);
await runRankingProtectionChecks();
await runScheduleChecks({worker,env,origin});
await runWeeklyResultsChecks();
await runMatchProgressChecks();
await runProgressUIChecks();
await runLiveCourtsChecks({worker,env,origin,db});
await runLiveUIChecks();
await runServerAuditChecks();
await runClientAuditChecks();
await runSubstitutionChecks();
await runEmergencyUIChecks();
await runOperatorNavChecks();
console.log('PASS: correct/incorrect passwords, 5-attempt limit, expiry, origin checks, missing configuration, public secret isolation, existing operator route and unauthenticated write rejection.');
if(process.argv.includes('--serve')){
  env.OPERATOR_PASSWORD=process.env.OPERATOR_PASSWORD||'test-password';
  const previewPort=Number(process.env.KOKKIRI_PREVIEW_PORT||4173);
  assert.ok(Number.isInteger(previewPort)&&previewPort>=1024&&previewPort<=65535,'유효한 로컬 미리보기 포트가 필요합니다');
  createServer(async(req,res)=>{
    if(req.url.startsWith('/__mobile')){
      const view=new URL(req.url,origin).searchParams.get('view'),hash=view==='home'?'home':view==='schedule'?'post/schedule-ui-test':'live';
      res.writeHead(200,{'content-type':'text/html; charset=utf-8'});
      res.end('<!doctype html><html><head><title>390px local preview</title></head><body style="margin:0;background:#ddd"><iframe title="390px mobile preview" src="/#'+hash+'" style="width:390px;height:844px;border:0;display:block"></iframe></body></html>');return;
    }
    try{const chunks=[];for await(const chunk of req)chunks.push(chunk);
      const previewOrigin='http://'+(req.headers.host||'localhost:'+previewPort);
      const r=await worker.fetch(new Request(previewOrigin+req.url,{method:req.method,headers:req.headers,...(['GET','HEAD'].includes(req.method)?{}:{body:Buffer.concat(chunks)})}),env);
      res.writeHead(r.status,Object.fromEntries(r.headers));res.end(Buffer.from(await r.arrayBuffer()));
    }catch{res.writeHead(500);res.end('Preview unavailable');}
  }).listen(previewPort,'127.0.0.1',()=>console.log('Local URL: http://localhost:'+previewPort));
}
